name: Test total-llvm-sys with concrete LLVM version

on:
  workflow_dispatch:
    inputs:
      llvm-version:
        description: "LLVM version"
        required: true
        type: choice
        options:
          - 22
          - 21
      runner:
        description: "GitHub runner's OS"
        required: true
        type: choice
        options:
          - windows-2025
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - macos-26
          - macos-26-arm

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  test-total-llvm-sys:
    runs-on: ${{ github.event.inputs.runner }}

    timeout-minutes: 60

    steps:
      - name: Display build info
        run: |
          echo "Runner OS: ${{ github.event.inputs.runner }}"
          echo "Runner arch: $RUNNER_ARCH"
          echo "LLVM version: ${{ github.event.inputs.llvm-version }}"
          echo "Release tag: ${{ github.event.inputs.tag }}"

      - name: Checkout repository
        uses: actions/checkout@v6
      
      - name: Build total-llvm-sys
        run: |
          cargo build --features="llvm-${{ github.event.inputs.llvm-version }}"
      
      - name: Test total-llvm-sys
        run: |
          cargo test --features="llvm-${{ github.event.inputs.llvm-version }}"

      - name: Build total-llvm-sys release
        run: |
          cargo build -r --features="llvm-${{ github.event.inputs.llvm-version }}"
      
      - name: Test total-llvm-sys release
        run: |
          cargo test -r --features="llvm-${{ github.event.inputs.llvm-version }}"

